version: '3.8'

services:
  postgresql:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: visu_clientes
    volumes:
      - ./dados-postgresql/postgres:/var/lib/postgresql/data
      - ./migrations:/migrations
    ports:
      - "5432:5432"

  teste-php:
    build: .
    container_name: teste-php
    volumes:
      - ./src:/var/www/html
    depends_on:
      - postgresql

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - teste-php
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "4000:4000"
    depends_on:
      - teste-php